name: ğŸ“¦ Update package summary

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1-5" # Every weekday at 8:00 AM

jobs:
  update_markdown_file:
    name: ğŸ“ƒ Update markdown file
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checking out code
        uses: actions/checkout@v3

      - name: ğŸ” Finding latest version info & updating file
        run: node scripts/GeneratePackageMarkdown.js

      - name: â¬†ï¸ Committing changes to markdown file
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          message: "Updated Package Info"
